name: jest
on: push
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup
    - run: node -v
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: node -v
    - run: yarn install
    - run: yarn run test
